name: zavisoft_task
description: Base GetX boilerplate project
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  intl: ^0.20.2
  logger: ^2.6.2
